import Head from "next/head";
import styles from "../../styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.css";
import Web3Modal from "web3modal";
import { useEffect, useRef, useState, useMemo } from "react";
import { Player } from "@livepeer/react";
import { ethers } from "ethers";
import { subgraphQuery } from "../../utils";
import { useRouter } from "next/router";
import { render } from "react-dom";
import { resolve } from "styled-jsx/css";
import Link from 'next/link'

export default function Video({ pageDisplay, setPageDisplay }) {
  const router = useRouter();

  const [data, setData] = useState(null);
  const [relatedVideos, setRelatedVideos] = useState([]);


  const getVideo = async () => {
    
    const query = `query{
        videoUploadeds(where: {location: "${router.query.id}"}) {
            id
            videoNumber
            date
            location
            title
            description
            category
            owner
        }
      }`;

    const data = await subgraphQuery(query);
    setData(data.videoUploadeds[0]);
    console.log(data.videoUploadeds[0]);
    const category = data.videoUploadeds[0].category;
    const query2 = `query{
       videoUploadeds(where: {category: "${category}"}, orderBy: videoNumber, orderDirection: desc) {
           id
           videoNumber
           date
           location
           title
           description
           category
           owner
       }
    }`
    const data2 = await subgraphQuery(query2);
    setRelatedVideos(data2.videoUploadeds);
    console.log(data2.videoUploadeds);
  };
  
    useEffect(() => { 
        getVideo();
    },[]);

    useEffect(() => { 
        getVideo();
    },[router.query.id]);
  
  console.log("data: " + data);

  return (
    <>
      <Head>
        <title>BlockTube</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={styles.main}
        style={{ minHeight: "100vh", height: "auto", paddingBottom: "100px" }}
      >
        <div style={{ height: "30px", width: "150px" }}>
         <Link href="../"><img src="/favicon.ico" alt="logo" className={styles.favicon} /></Link> 
        </div>

        <div className="container-fluid" style={{marginTop: "90px"}}>
          <div className="row">
            <div className="col-sm-10 col-md-8 col-lg-8 col-xl-8" style={{minHeight: "200px", maxHeight: "500px"}}>
               {data ?
              <Player
              title={data.title}
              playbackId={data.location}
              showPipButton
              showTitle={false}
              aspectRatio="16to16"
              controls={{
                autohide: 3000,
              }}
              theme={{
                borderStyles: { containerBorderStyle: "hidden" },
                radii: { containerBorderRadius: "10px" },
              }}
            />  : <h1>Loading...</h1>}
            <br />
             {data ? <><span className="mt-2 m-3 fs-5 fw-semibold">{data.title}</span> <span style={{marginLeft: "480px", fontWeight: "700"}} className={styles.address}>{data.owner.slice(0,6) + "..." + data.owner.slice(-4)}</span></> : <></>}

             {data  ? <div className={styles.description}>
              <p className="fw-semibold fs-5">Description: </p>
               <span style={{ fontSize: "18px", fontWeight: "450"}}> {data.description} </span>
             </div> : <></>}

            </div>
            <div className="col-sm-2 col-md-4 col-lg-4 col-xl-4">
            { relatedVideos.map((video) => (
          <div style={{ width: "400px", height: "240px", marginTop: "20px", cursor: "pointer", paddingBottom: "20px" }}>
            <Player
              title={video.title}
              playbackId={video.location}
              showPipButton
              showTitle={false}
              aspectRatio="16to16"
              controls={{
                autohide: 3000,
              }}
              theme={{
                borderStyles: { containerBorderStyle: "hidden" },
                radii: { containerBorderRadius: "10px" },
              }}
            />
            <Link href='/videos/[id]' as={'/videos/' + video.location}>{video.title}</Link>
          </div>
        ))}
            </div>
          </div>
        </div>

       
      </main>
    </>
  );
}
